/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import ProyectoED.LectordeMedline;
import arboles.ArbolAVL;

import java.util.ArrayList;
import java.util.List;

import ordenamiento.BusquedaBinaria;
import ordenamiento.MergeSort;
import ordenamiento.ShellSort;

/**
 *
 * @author jeusm
 */
public class View extends javax.swing.JFrame {

    final LectordeMedline LECTOR = new LectordeMedline();
    final List<String> PALABRAS = LectordeMedline.readAndProcessFile("medline_CDs.txt");

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscador");

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Palabra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        long inicio = 0, fin = 0, burbuja = 0, insercion = 0, shellsort = 0, quicksort = 0, mergesort = 0, mezcla = 0, abb = 0, avl = 0, ab = 0;
        String palabra = txtInput.getText().toLowerCase();
        List<String> ordenado;
        ShellSort<String> ss = new ShellSort(new ArrayList<>(PALABRAS));
        MergeSort<String> ms = new MergeSort<>();

        //shellsort
        inicio = System.currentTimeMillis();
        ss.sort();
        BusquedaBinaria.busquedaBinaria(ss.getArr(), palabra);
        fin = System.currentTimeMillis();
        shellsort = fin - inicio;

        //MergeSort
        inicio = System.currentTimeMillis();
        ordenado = new ArrayList<>(PALABRAS);
        ordenado = ms.ordenaMerge(ordenado);
        BusquedaBinaria.busquedaBinaria(ordenado, palabra);
        fin = System.currentTimeMillis();
        mergesort = fin - inicio;

        //AVL
        inicio = System.currentTimeMillis();
        ArbolAVL<String> arbolAvl = new ArbolAVL<>(PALABRAS.get(0));
        //arbol avl no inserta duplicados, ya lo comprobé, asi que en este caso no pasa nada
        for (String e : PALABRAS) {
            arbolAvl.insertar(e);
        }
        arbolAvl.buscar(palabra);
        fin = System.currentTimeMillis();
        avl = fin - inicio;

        System.out.println("Estadisticas: ");
        // metodos de ordenamiento
        System.out.println("Burbuja: " + burbuja + " ms");
        System.out.println("Insercion: " + insercion + " ms");
        System.out.println("ShellSort: " + shellsort + " ms");
        System.out.println("Quicksort: " + quicksort + " ms");
        System.out.println("MergeSort: " + mergesort + " ms");
        System.out.println("Mezcla homogenea: " + mezcla + " ms");

        //arboles
        System.out.println("Arboles Binarios de Busqueda: " + abb + " ms");
        System.out.println("Arboles AVL: " + avl + " ms");
        System.out.println("Arboles B: " + ab + " ms");
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
